on:
  - push
jobs:
  build: null
  name: Hello world
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@3
    - name: Write a multiline message
      run: |
        echo This demo file shows a 
        echo very basic and easy-to-understand workflow
